consumer:
  topic: "some_topic"
  bootstrap-servers: "127.0.0.1:9092"
  group-id: "some_group"
  auto-offset-reset: "earliest"

logging:
  level:
    root: info

spring:
  redis:
    host: "localhost"
    port: 6379
  main:
    web-application-type: none
