version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
